/**
 * UPLDisclaimer — Non-dismissible Unauthorized Practice of Law shield
 *
 * Must appear on EVERY screen that displays AI-generated legal content.
 * Cannot be hidden, minimized, or removed by users.
 * Legal requirement: ABA Model Rule 5.5 / state UPL statutes.
 */
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { COLORS } from '../constants/theme';

interface Props {
  compact?: boolean;   // one-line version for tight spaces
  attorney?: boolean;  // attorney-platform variant
}

export default function UPLDisclaimer({ compact, attorney }: Props) {
  if (compact) {
    return (
      <View style={s.compact}>
        <Text style={s.compactText} maxFontSizeMultiplier={1.2} accessibilityRole="text">
          ⚖️ AI-generated — not legal advice. Consult a licensed attorney.
        </Text>
      </View>
    );
  }
  return (
    <View style={s.banner} accessibilityRole="text" accessibilityLabel="Legal disclaimer">
      <Text style={s.icon}>⚖️</Text>
      <View style={s.textBlock}>
        <Text style={s.heading} maxFontSizeMultiplier={1.3}>
          {attorney ? 'For Attorney Review Only' : 'Not Legal Advice'}
        </Text>
        <Text style={s.body} maxFontSizeMultiplier={1.3}>
          {attorney
            ? 'This AI-generated content is a drafting aid only. You are responsible for verifying accuracy, jurisdiction-specific rules, and professional judgment before relying on or sharing this with clients.'
            : 'This information is generated by AI and is for general educational purposes only. It is not legal advice and does not create an attorney-client relationship. Laws vary by state and change frequently. Always consult a licensed attorney for advice specific to your situation.'}
        </Text>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  banner:      { flexDirection: 'row', backgroundColor: '#FFF8E1', borderLeftWidth: 3, borderLeftColor: '#F9A825', padding: 12, margin: 12, marginTop: 0, borderRadius: 6 },
  icon:        { fontSize: 18, marginRight: 10, marginTop: 1 },
  textBlock:   { flex: 1 },
  heading:     { fontSize: 12, fontWeight: '700', color: '#5D4037', marginBottom: 3, textTransform: 'uppercase', letterSpacing: 0.5 },
  body:        { fontSize: 11, color: '#5D4037', lineHeight: 16 },
  compact:     { backgroundColor: '#FFF8E1', paddingHorizontal: 12, paddingVertical: 6, borderTopWidth: 1, borderTopColor: '#F9A825' },
  compactText: { fontSize: 11, color: '#5D4037', textAlign: 'center' },
});
