CREATE TABLE IF NOT EXISTS forum_posts (id INTEGER PRIMARY KEY AUTOINCREMENT,user_handle TEXT,title TEXT,body TEXT,created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS forum_replies (id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER,user_handle TEXT,body TEXT,created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS lessons (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,category TEXT,content TEXT,points INTEGER DEFAULT 10);
CREATE TABLE IF NOT EXISTS lesson_progress (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,lesson_id INTEGER,completed INTEGER DEFAULT 0,completed_at TEXT);
CREATE TABLE IF NOT EXISTS referrals (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,owner_user_id INTEGER,credits INTEGER DEFAULT 0,created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS rewards (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER UNIQUE,points INTEGER DEFAULT 0,updated_at TEXT DEFAULT (datetime('now')));
