import React, { useState } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, Linking, Alert,
} from 'react-native';
import { COLORS } from '../constants/theme';

const SECTIONS = [
  {
    title: 'Attorney-Client Privilege',
    icon: '⚖️',
    body: `Justice Gavel is a legal technology platform, not your client's legal representative. All data you enter into the platform is subject to your existing attorney-client privilege obligations.

We do not access, review, or use matter data for any purpose other than delivering platform services to you. Your client communications remain privileged — our infrastructure is the conduit, not the content.`,
  },
  {
    title: 'Data Segregation',
    icon: '🔒',
    body: `Each attorney account is logically isolated. Firm-level data (matters, client information, case notes) is accessible only to authenticated members of your firm as configured by your firm administrator.

No data crosses firm boundaries. Law Firm A cannot access Law Firm B's matters, clients, or communications under any circumstance.`,
  },
  {
    title: 'Professional Responsibility Compliance',
    icon: '📋',
    body: `Justice Gavel is designed to help attorneys comply with professional responsibility obligations:

• ABA Model Rule 1.1 (Competence): AI-generated signals carry mandatory disclaimers. No output replaces attorney judgment.

• ABA Model Rule 1.6 (Confidentiality): We do not sell, share, or monetize client data. Zero third-party data sharing except as required for platform operation (hosting, AI inference).

• ABA Model Rule 5.3 (Non-lawyer supervision): All AI-generated content is advisory only and labeled as such. The attorney of record remains responsible for all legal advice.`,
  },
  {
    title: 'Data Storage & Security',
    icon: '🛡️',
    body: `• Data at rest: AES-256 encryption
• Data in transit: TLS 1.3 minimum
• AI inference: Anthropic API (SOC 2 Type II certified)
• Payments: Stripe (PCI DSS Level 1)
• Infrastructure: Railway (SOC 2 Type II)
• Database: Supabase on AWS (SOC 2 Type II)

No client data is used to train AI models. You may request complete deletion of your firm's data at any time by contacting privacy@justicegavel.app.`,
  },
  {
    title: 'BAA / Data Processing Agreement',
    icon: '📄',
    body: `For firms requiring a formal Business Associate Agreement (BAA) or Data Processing Agreement (DPA), contact legal@justicegavel.app.

Justice Gavel is not itself a covered entity under HIPAA, but we understand that law firms handling healthcare-adjacent matters may require formal data processing documentation.

For public defender offices and court-appointed counsel programs, we offer government-specific data agreements. Contact partnerships@justicegavel.app.`,
  },
  {
    title: 'Ethical Walls & Conflict Screening',
    icon: '🚧',
    body: `Ethical wall functionality is available for firms with conflict-of-interest screening requirements. Attorneys screened from a matter cannot access it, regardless of firm role.

Conflict checks run automatically when new matters are opened. Your firm administrator can configure the conflict screening parameters in Firm Settings.`,
  },
  {
    title: 'AI Disclaimer',
    icon: '🤖',
    body: `All AI-generated content — including matter intelligence signals, motion recommendations, outcome estimates, and chat responses — carries the following disclaimer:

"This output is generated by artificial intelligence and is provided for informational purposes only. It does not constitute legal advice and should not be relied upon without independent verification by a licensed attorney. Justice Gavel, Inc. assumes no liability for decisions made based on AI-generated content."

This disclaimer is non-removable and appears on all AI output delivered to clients.`,
  },
];

export default function AttorneyPrivacyScreen({ navigation }: any) {
  const colors = COLORS;
  const [expanded, setExpanded] = useState<number | null>(0);

  return (
    <ScrollView
      style={{ flex: 1, backgroundColor: COLORS.bg }}
      contentContainerStyle={s.container}
    >
      {/* Header */}
      <View style={[s.header, { backgroundColor: COLORS.navy }]}>
        <Text style={s.headerIcon}>🔏</Text>
        <Text style={s.headerTitle}>Attorney Platform Privacy</Text>
        <Text style={s.headerSub}>
          Data policy, professional responsibility compliance,
          and BAA information for law firm subscribers
        </Text>
      </View>

      {/* Effective date */}
      <View style={[s.effectiveBadge, { backgroundColor: COLORS.bgCard, borderColor: COLORS.border }]}>
        <Text style={[s.effectiveText, { color: COLORS.textMuted }]}>
          Effective: January 1, 2026 · Version 2.1
        </Text>
        <TouchableOpacity
          accessibilityRole="button"
          accessibilityLabel="Full Privacy Policy \u2192" onPress={() => Linking.openURL('https://justicegavel.app/privacy').catch(() => {})}
        >
          <Text style={[s.fullPolicyLink, { color: COLORS.navy }]}>Full Privacy Policy →</Text>
        </TouchableOpacity>
      </View>

      {/* Accordion sections */}
      {SECTIONS.map((sec, idx) => (
        <View
          key={idx}
          style={[s.section, { backgroundColor: COLORS.bgCard, borderColor: COLORS.border }]}
        >
          <TouchableOpacity
            accessibilityRole="button"
            style={s.sectionHeader}
            accessibilityLabel="{sec.icon}" onPress={() => setExpanded(expanded === idx ? null : idx)}
          >
            <Text style={s.sectionIcon}>{sec.icon}</Text>
            <Text style={[s.sectionTitle, { color: COLORS.textPrimary, flex: 1 }]}>
              {sec.title}
            </Text>
            <Text style={[s.chevron, { color: COLORS.textMuted }]}>
              {expanded === idx ? '▲' : '▼'}
            </Text>
          </TouchableOpacity>
          {expanded === idx && (
            <View style={[s.sectionBody, { borderTopColor: COLORS.border }]}>
              <Text style={[s.bodyText, { color: COLORS.textSecond }]}>
                {sec.body}
              </Text>
            </View>
          )}
        </View>
      ))}

      {/* Contact block */}
      <View style={[s.contactBlock, { backgroundColor: COLORS.bgCard, borderColor: COLORS.border }]}>
        <Text style={[s.contactTitle, { color: COLORS.textPrimary }]}>Need a BAA or DPA?</Text>
        <Text style={[s.contactBody, { color: COLORS.textSecond }]}>
          Contact our legal team to request a Business Associate Agreement,
          Data Processing Agreement, or custom data governance documentation
          for your jurisdiction.
        </Text>
        <TouchableOpacity
          accessibilityRole="button"
          style={[s.contactBtn, { backgroundColor: COLORS.navy }]}
          accessibilityLabel="Contact Legal Team" onPress={() => Linking.openURL('mailto:legal@justicegavel.app').catch(() => Alert.alert('Email', 'legal@justicegavel.app'))}
        >
          <Text style={s.contactBtnText}>Contact Legal Team</Text>
        </TouchableOpacity>
        <TouchableOpacity
          accessibilityRole="button"
          style={[s.contactBtn, s.contactBtnOutline, { borderColor: COLORS.navy }]}
          onPress={() => Linking.openURL('mailto:privacy@justicegavel.app').catch(() => Alert.alert('Email', 'privacy@justicegavel.app'))}
        >
          <Text style={[s.contactBtnText, { color: COLORS.navy }]}>Request Data Deletion</Text>
        </TouchableOpacity>
      </View>

      <View style={{ height: 40 }} />
    </ScrollView>
  );
}

const s = StyleSheet.create({
  container:        { padding: 0, paddingBottom: 24 },
  header:           { padding: 28, paddingTop: 52, alignItems: 'center' },
  headerIcon:       { fontSize: 40, marginBottom: 12 },
  headerTitle:      { fontSize: 22, fontWeight: '800', color: '#fff', textAlign: 'center', marginBottom: 8 },
  headerSub:        { fontSize: 14, color: 'rgba(255,255,255,0.82)', textAlign: 'center', lineHeight: 20 },
  effectiveBadge:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1, marginHorizontal: 0 },
  effectiveText:    { fontSize: 12 },
  fullPolicyLink:   { fontSize: 12, fontWeight: '600' },
  section:          { marginHorizontal: 16, marginTop: 12, borderRadius: 12, borderWidth: 1, overflow: 'hidden' },
  sectionHeader:    { flexDirection: 'row', alignItems: 'center', padding: 16 },
  sectionIcon:      { fontSize: 22, marginRight: 12 },
  sectionTitle:     { fontSize: 15, fontWeight: '700', lineHeight: 20 },
  chevron:          { fontSize: 12, marginLeft: 8 },
  sectionBody:      { padding: 16, paddingTop: 12, borderTopWidth: 1 },
  bodyText:         { fontSize: 14, lineHeight: 22 },
  contactBlock:     { margin: 16, marginTop: 24, borderRadius: 12, borderWidth: 1, padding: 20 },
  contactTitle:     { fontSize: 17, fontWeight: '700', marginBottom: 8 },
  contactBody:      { fontSize: 14, lineHeight: 20, marginBottom: 16 },
  contactBtn:       { paddingVertical: 13, borderRadius: 10, alignItems: 'center', marginBottom: 10 },
  contactBtnOutline:{ backgroundColor: 'transparent', borderWidth: 1.5 },
  contactBtnText:   { color: '#fff', fontSize: 14, fontWeight: '700' },
});
