/**
 * TermsOfServiceScreen
 *
 * Full Terms of Service -- required by Apple App Store and Google Play.
 * Accessible from: Settings → Terms of Service
 * Also shown inline during Onboarding (first-time accept flow).
 *
 * Legal notices:
 *  • Not a law firm and does not provide legal advice
 *  • AI output is informational only
 *  • Unauthorized Practice of Law disclaimer
 *  • Subscription and refund terms
 *  • Encounter Recorder recording law notice
 */
import React, { useRef } from 'react';
import type { ScreenProps } from '../types/navigation';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, Linking,
} from 'react-native';
import { hapticImpact, hapticNotification, hapticSelection } from '../utils/webCompat';
import {useTheme} from '../constants/theme';

const EFFECTIVE_DATE = 'May 1, 2026';
const COMPANY       = 'Justice Gavel LLC';
const CONTACT_EMAIL = 'legal@justicegavel.app';
const WEBSITE       = 'https://justicegavel.app';

type Section = { heading: string; body: string };

const SECTIONS: Section[] = [
  {
    heading: '1. What Justice Gavel Is -- and Is Not',
    body:
      'Justice Gavel is a legal information and attorney connection platform. ' +
      'We are NOT a law firm. Nothing on this platform -- including any ' +
      'output from our AI assistant -- constitutes legal advice, creates an ' +
      'attorney-client relationship, or should be relied upon as a substitute ' +
      'for consultation with a licensed attorney.\n\n' +
      'The AI assistant provides general legal information based on publicly ' +
      'available law. It does not know the specific facts of your case, your ' +
      'jurisdiction\'s local rules, or your judge\'s preferences. Always consult ' +
      'a licensed criminal defense attorney for advice specific to your situation.',
  },
  {
    heading: '2. Eligibility',
    body:
      'You must be at least 18 years old to create an account. By using Justice ' +
      'Gavel, you represent that you are 18 or older and have the legal capacity ' +
      'to enter into these Terms. Users under 18 may use the app in browse-only ' +
      'mode with guardian consent, but may not create accounts or subscribe.',
  },
  {
    heading: '3. Your Account',
    body:
      'You are responsible for maintaining the confidentiality of your account ' +
      'credentials and for all activity that occurs under your account. Notify us ' +
      'immediately at ' + CONTACT_EMAIL + ' if you suspect unauthorized access.\n\n' +
      'We may suspend or terminate accounts that violate these Terms, engage in ' +
      'fraudulent activity, or attempt to misuse the platform.',
  },
  {
    heading: '4. AI Legal Assistant -- Important Limitations',
    body:
      'Our AI assistant is powered by large language models (LLMs) that can make ' +
      'mistakes, hallucinate statutes that do not exist, and misstate the law. ' +
      'You should:\n\n' +
      '• Verify all information with a licensed attorney before acting on it\n' +
      '• Never use AI output as a substitute for professional legal counsel\n' +
      '• Understand that AI responses do not account for recent legal changes\n' +
      '• Recognize that legal outcomes depend on facts, jurisdiction, and strategy\n\n' +
      'We expressly disclaim liability for any harm resulting from reliance on ' +
      'AI-generated content without independent professional verification.',
  },
  {
    heading: '5. Encounter Recorder -- Recording Consent',
    body:
      'The Encounter Recorder feature records audio of police encounters. ' +
      'Recording laws vary by state. You are solely responsible for ensuring ' +
      'your use of this feature complies with applicable law in your jurisdiction.\n\n' +
      'In two-party (all-party) consent states, recording without all parties\' ' +
      'consent may be unlawful. The app displays a consent warning based on your ' +
      'detected state, but this warning is informational only and may not reflect ' +
      'current law or all applicable exceptions.\n\n' +
      'Justice Gavel accepts no liability for recordings made in violation of ' +
      'applicable law. Transcripts generated by AI may contain errors and are not ' +
      'certified legal transcripts.',
  },
  {
    heading: '6. Attorney and Bail Agent Listings',
    body:
      'Attorney and bail agent listings on Justice Gavel are provided for ' +
      'informational purposes only. We do not endorse any specific attorney or ' +
      'bail agent, guarantee their availability, verify all credentials in ' +
      'real time, or accept responsibility for the quality of services they provide.\n\n' +
      'Always independently verify an attorney\'s bar membership status through ' +
      'your state bar association before engaging their services.',
  },
  {
    heading: '7. Subscriptions and Payments',
    body:
      'Some features require a paid subscription. Subscriptions auto-renew unless ' +
      'cancelled at least 24 hours before the renewal date.\n\n' +
      'iOS: Subscriptions are managed through your Apple ID. You may cancel in ' +
      'Settings → [Your Name] → Subscriptions. Refunds are subject to Apple\'s ' +
      'refund policy.\n\n' +
      'Android: Subscriptions are managed through your Google Play account. ' +
      'Cancel in Google Play → Subscriptions.\n\n' +
      'Web/direct: Subscriptions are processed by Stripe. You may cancel at any ' +
      'time from Settings. Refunds within 48 hours of initial purchase are ' +
      'available upon request at ' + CONTACT_EMAIL + '.',
  },
  {
    heading: '8. Privacy',
    body:
      'Your use of Justice Gavel is also governed by our Privacy Policy, which is ' +
      'incorporated into these Terms by reference. The Privacy Policy explains what ' +
      'data we collect, how we use it, and your rights regarding your data.\n\n' +
      'We do not sell your personal information to third parties.',
  },
  {
    heading: '9. Prohibited Conduct',
    body:
      'You may not use Justice Gavel to:\n\n' +
      '• Attempt to circumvent, hack, or reverse-engineer any part of the platform\n' +
      '• Scrape, harvest, or systematically extract attorney or provider data\n' +
      '• Submit false, fraudulent, or misleading information\n' +
      '• Harass, threaten, or harm other users or attorneys\n' +
      '• Use the platform in violation of any applicable law\n' +
      '• Impersonate attorneys, law enforcement, or Justice Gavel staff',
  },
  {
    heading: '10. Intellectual Property',
    body:
      'All content, features, and functionality of Justice Gavel -- including but ' +
      'not limited to text, graphics, logos, and software -- are the exclusive ' +
      'property of ' + COMPANY + ' and are protected by copyright, trademark, ' +
      'and other applicable laws.\n\n' +
      'You may not reproduce, distribute, or create derivative works from any ' +
      'part of the platform without our express written permission.',
  },
  {
    heading: '11. Disclaimer of Warranties',
    body:
      'JUSTICE GAVEL IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES ' +
      'OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE ' +
      'SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES.\n\n' +
      'TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES ' +
      'INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR ' +
      'PURPOSE, AND NON-INFRINGEMENT.',
  },
  {
    heading: '12. Limitation of Liability',
    body:
      'TO THE MAXIMUM EXTENT PERMITTED BY LAW, ' + COMPANY.toUpperCase() + ' ' +
      'SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, ' +
      'OR PUNITIVE DAMAGES, INCLUDING LOSS OF DATA OR PROFITS, ARISING FROM YOUR ' +
      'USE OF OR INABILITY TO USE THE SERVICE.\n\n' +
      'OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM SHALL NOT EXCEED THE GREATER OF ' +
      '$100 OR THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM.',
  },
  {
    heading: '13. Indemnification',
    body:
      'You agree to defend, indemnify, and hold harmless Justice Gavel, its officers, ' +
      'directors, employees, and agents from and against any claims, damages, obligations, ' +
      'losses, liabilities, costs, or debt arising from: (a) your use of the Service; ' +
      '(b) your violation of these Terms; (c) your violation of any third-party rights, ' +
      'including any intellectual property or privacy rights; or (d) any claim that your ' +
      'content caused damage to a third party. This indemnification obligation will survive ' +
      'the termination of these Terms and your use of the Service.',
  },
  {
    heading: '13. Governing Law & Dispute Resolution',
    body:
      'These Terms are governed by the laws of the State of Tennessee, without ' +
      'regard to conflict of law principles.\n\n' +
      'Any dispute arising out of or relating to these Terms or the Service shall ' +
      'be resolved by binding arbitration under the AAA Consumer Arbitration Rules, ' +
      'except that either party may seek injunctive relief in a court of competent ' +
      'jurisdiction. You waive any right to a jury trial or to participate in a ' +
      'class action.',
  },
  {
    heading: '14. Changes to These Terms',
    body:
      'We may update these Terms from time to time. When we do, we will update the ' +
      '"Effective Date" above and notify you via the app or email. Continued use of ' +
      'Justice Gavel after changes constitutes acceptance of the updated Terms.',
  },
  {
    heading: '15. Contact Us',
    body:
      COMPANY + '\n' +
      'Email: ' + CONTACT_EMAIL + '\n' +
      'Website: ' + WEBSITE + '\n\n' +
      'For legal inquiries, attorney verification issues, or to report misuse, ' +
      'please contact us at the email above.',
  },
];

export default function TermsOfServiceScreen({ navigation }: ScreenProps): React.JSX.Element {
  const { colors, isDark } = useTheme();
  const scrollRef = useRef<ScrollView>(null);

  const openEmail = () => {
    hapticImpact();
    Linking.openURL(`mailto:${CONTACT_EMAIL}`).catch(() => {});
  };

  return (
    <ScrollView
      ref={scrollRef}
      style={{ flex: 1, backgroundColor: colors.bg }}
      contentContainerStyle={styles.scroll}
      showsVerticalScrollIndicator={false}
    >
      {/* ── Header ──────────────────────────────────────────────── */}
      <View style={[styles.header, { backgroundColor: colors.navy }]}>
        <Text maxFontSizeMultiplier={1.2} style={styles.headerEyebrow}>
          JUSTICE GAVEL
        </Text>
        <Text maxFontSizeMultiplier={1.2} style={styles.headerTitle}>
          Terms of Service
        </Text>
        <Text maxFontSizeMultiplier={1.3} style={styles.headerMeta}>
          Effective {EFFECTIVE_DATE}
        </Text>
      </View>

      {/* ── Critical notice ─────────────────────────────────────── */}
      <View style={[styles.noticeBox, { backgroundColor: isDark ? colors.surface : colors.warnBg,
        borderLeftColor: colors.warnDark }]}>
        <Text maxFontSizeMultiplier={1.3} style={[styles.noticeTitle,
          { color: colors.warnDark }]}>
          ⚖️ Not Legal Advice
        </Text>
        <Text maxFontSizeMultiplier={1.3} style={[styles.noticeBody,
          { color: isDark ? colors.warn : colors.textMuted }]}>
          Justice Gavel provides legal information, not legal advice.
          We are not a law firm. Nothing here creates an attorney-client relationship.
          Always consult a licensed attorney for advice specific to your situation.
        </Text>
      </View>

      {/* ── Sections ────────────────────────────────────────────── */}
      {SECTIONS.map((section, idx) => (
        <View key={idx} style={[styles.section, { backgroundColor: colors.bgCard,
          borderLeftColor: idx === 0 ? colors.emergency :
                          idx === 4 ? colors.warnDark :
                          idx === 6 ? colors.legal : colors.border }]}>
          <Text maxFontSizeMultiplier={1.2} style={[styles.sectionHeading,
            { color: colors.textPrimary }]}>
            {section.heading}
          </Text>
          <Text maxFontSizeMultiplier={1.3} style={[styles.sectionBody,
            { color: colors.textSecond }]}>
            {section.body}
          </Text>
        </View>
      ))}

      {/* ── Footer CTA ──────────────────────────────────────────── */}
      <View style={[styles.footer, { backgroundColor: colors.bgCard }]}>
        <Text maxFontSizeMultiplier={1.3} style={[styles.footerText,
          { color: colors.textMuted }]}>
          Questions about these Terms?
        </Text>
        <TouchableOpacity
          onPress={openEmail}
          style={[styles.footerBtn, { borderColor: colors.border }]}
          accessibilityRole="link"
          accessibilityLabel="Email legal@justicegavel.app"
        >
          <Text maxFontSizeMultiplier={1.3} style={[styles.footerBtnText,
            { color: colors.blue }]}>
            📧 {CONTACT_EMAIL}
          </Text>
        </TouchableOpacity>
        <Text maxFontSizeMultiplier={1.3} style={[styles.footerCopy,
          { color: colors.textFaint }]}>
          © {new Date().getFullYear()} {COMPANY}. All rights reserved.{'\n'}
          Innocent until proven guilty.
        </Text>
      </View>

      <View style={{ height: 48 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll:          { paddingBottom: 32 },
  header:          { padding: 28, paddingTop: 48 },
  headerEyebrow:   { color: 'rgba(133,183,235,0.8)', fontSize: 11, fontWeight: '800',
                     letterSpacing: 3, marginBottom: 6 },
  headerTitle:     { color: '#fff', fontSize: 28, fontWeight: '900', marginBottom: 8 },
  headerMeta:      { color: 'rgba(255,255,255,0.6)', fontSize: 12 },
  noticeBox:       { margin: 16, borderRadius: 12, padding: 16, borderLeftWidth: 5 },
  noticeTitle:     { fontSize: 14, fontWeight: '800', marginBottom: 6 },
  noticeBody:      { fontSize: 13, lineHeight: 20 },
  section:         { marginHorizontal: 16, marginBottom: 12, borderRadius: 12,
                     padding: 18, borderLeftWidth: 4 },
  sectionHeading:  { fontSize: 14, fontWeight: '800', marginBottom: 10, lineHeight: 20 },
  sectionBody:     { fontSize: 13, lineHeight: 21 },
  footer:          { margin: 16, borderRadius: 14, padding: 24, alignItems: 'center', gap: 12 },
  footerText:      { fontSize: 13 },
  footerBtn:       { borderWidth: 1, borderRadius: 10, paddingVertical: 12,
                     paddingHorizontal: 20 },
  footerBtnText:   { fontSize: 13, fontWeight: '700' },
  footerCopy:      { fontSize: 11, textAlign: 'center', lineHeight: 17 },
});
