/**
 * middleware/disclaimer.js — Disclaimer versioning & acceptance tracking
 *
 * LEGAL PROTECTION: The current legal disclaimer version is stored in DB.
 * Every user's acceptance is timestamped and IP-logged.
 * When the disclaimer text changes (new version published), users must
 * re-accept on next app launch before accessing any AI features.
 *
 * This creates a verifiable consent trail that protects against:
 *   - UPL claims ("users were not warned")
 *   - Malpractice claims ("the app said it was legal advice")
 *   - CCPA/GDPR claims ("users did not consent to data processing")
 */

import { getDb }  from '../db/index.js';
import logger     from '../utils/logger.js';

// Current disclaimer version — bump when legal text changes
// Format: YYYY-MM-DD.N  (date + revision number)
export const CURRENT_DISCLAIMER_VERSION = '2026-01-01.1';

export const DISCLAIMER_TEXT = `
IMPORTANT LEGAL NOTICE — PLEASE READ CAREFULLY

Justice Gavel is a legal information and technology platform.
It is NOT a law firm and does NOT provide legal advice.

All content generated by artificial intelligence — including legal research,
motion drafts, case analysis, signal alerts, and chat responses — is for
INFORMATIONAL PURPOSES ONLY. It does not constitute legal advice, create an
attorney-client relationship, or substitute for consultation with a licensed attorney.

Laws vary by jurisdiction and change frequently. Information provided may not
reflect the most current legal developments. You should not act on any information
from this platform without first consulting a licensed attorney in your jurisdiction.

By using Justice Gavel you acknowledge and agree that:
1. This platform provides legal information, not legal advice.
2. No attorney-client relationship is formed by your use of this platform.
3. You will consult a licensed attorney before making any legal decisions.
4. Justice Gavel, Inc. and its licensors are not liable for actions taken
   in reliance on platform content.

For attorney emergencies: contact your state bar's lawyer referral service.
For life-threatening emergencies: call 911.
`.trim();

/**
 * Check if a user has accepted the current disclaimer version.
 * Returns { required: bool, version: string, text: string }
 */
export async function checkDisclaimerStatus(userId) {
  try {
    const db = await getDb();
    const row = await db.get(
      `SELECT accepted_at FROM user_disclaimer_acceptance
       WHERE user_id = ? AND version = ?`,
      [userId, CURRENT_DISCLAIMER_VERSION]
    );
    return {
      required: !row,
      version:  CURRENT_DISCLAIMER_VERSION,
      accepted: !!row,
      text:     row ? null : DISCLAIMER_TEXT,  // only send text when needed
    };
  } catch {
    return { required: false, version: CURRENT_DISCLAIMER_VERSION, accepted: true };
  }
}

/**
 * Record disclaimer acceptance.
 */
export async function recordDisclaimerAcceptance(userId, req) {
  try {
    const db = await getDb();
    await db.run(
      `INSERT OR REPLACE INTO user_disclaimer_acceptance
         (user_id, version, accepted_at, ip_address)
       VALUES (?, ?, datetime('now'), ?)`,
      [userId, CURRENT_DISCLAIMER_VERSION, req?.ip ?? null]
    );
    logger.info('[disclaimer] accepted', { userId, version: CURRENT_DISCLAIMER_VERSION });
    return { accepted: true, version: CURRENT_DISCLAIMER_VERSION };
  } catch (e) {
    logger.error('[disclaimer] Failed to record acceptance:', e.message);
    throw e;
  }
}

/**
 * Express middleware: blocks AI endpoints if disclaimer not accepted.
 * Apply to: /chat, /motions, /research, /discovery
 */
export async function requireDisclaimer(req, res, next) {
  if (!req.user?.id) return next();
  const status = await checkDisclaimerStatus(req.user.id);
  if (status.required) {
    return res.status(451).json({
      error:   'Legal disclaimer acceptance required.',
      code:    'disclaimer_required',
      version: status.version,
      text:    status.text,
    });
  }
  next();
}
