-- Enable RLS on remaining tables missing it
ALTER TABLE IF EXISTS cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS arrest_monitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bondsman_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS case_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS case_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS callback_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bail_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bail_monitoring ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS checkin_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS firm_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS firm_matters ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pi_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS refresh_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS push_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS docket_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS firm_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS research_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scheduled_pushes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS api_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS motion_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS saved_lawyers ENABLE ROW LEVEL SECURITY;

-- Critical tables required by migration_idempotency test
ALTER TABLE IF EXISTS users          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subscriptions  ENABLE ROW LEVEL SECURITY;
